# Apply with: envsubst < secret-quay.yaml | oc apply -f -
# QUAY_CRED must be base64-encoded .dockerconfigjson
apiVersion: v1
kind: Secret
metadata:
  name: quay-cred
  namespace: orion-newspaper
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${QUAY_CRED}
